services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services.
        autoconfigure: true # Enregistre automatiquement vos services en tant que commandes, abonnés d'événements, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Entity/'

    # Explicit configuration for ProductsRepository
    App\Repository\ProductsRepository:
        arguments:
            $entityClass: 'App\Entity\Products'

    # Explicit configuration for OrderRepository
    App\Repository\OrderRepository:
        arguments:
            $entityClass: 'App\Entity\Order' # Assurez-vous de remplacer 'App\Entity\Order' par le chemin réel de votre entité Order
